<%@ Page 
    Language="C#" 
    MasterPageFile="~/MasterPage.master" 
    AutoEventWireup="true" 
    CodeFile="Documentation-SiteMap.aspx.cs" 
    Inherits="RaWebsite.DocsSitemap" 
    Title="Ra-Ajax Documentation SiteMap" %>

<asp:Content 
    ID="Content1" 
    ContentPlaceHolderID="cnt1" 
    Runat="Server">

    <h1>Documentation SiteMap</h1>
    <p>
        This page is mostly created so that Google and other search engines will find 
        all our classes and tutorials. But it can also be a nice page to start out 
        surfing our documentation if you don't like the Ajax interface of the 
        <a href="Docs.aspx">main Ra-Ajax documentation page</a>.
    </p>
    <h2>Ra-Ajax Tutorials documentation</h2>
    <p>
        These tutorials ranges from noob level to quite advanced usage of Ra-Ajax. And even the noob
        tutorials often have some really interesting point about the core architecture and descisions
        behind Ra-Ajax. So even an experienced Ra-Ajax and ASP.NET developer will benefit a lot from 
        reading these tutorials.
    </p>
    <asp:Repeater runat="server" ID="repTutorials">
        <HeaderTemplate><ul class="list"></HeaderTemplate>
        <FooterTemplate></ul></FooterTemplate>
        <ItemTemplate>
            <li>
                <a href='<%#Eval("URL") %>'><%#Eval("Text") %></a>
            </li>
        </ItemTemplate>
    </asp:Repeater>
    <h2>Ra-Ajax Classes documentation</h2>
    <p>
        This is the classes reference documentation of Ra-Ajax and is autogenerated by 
        <a href="http://www.stack.nl/~dimitri/doxygen/">Doxygen</a> by using the XML
        output from Doxygen.
    </p>
    <asp:Repeater runat="server" ID="rep">
        <HeaderTemplate><ul class="list"></HeaderTemplate>
        <FooterTemplate></ul></FooterTemplate>
        <ItemTemplate>
            <li>
                <a href='<%#Eval("URL") %>'><%#Eval("Text") %></a>
            </li>
        </ItemTemplate>
    </asp:Repeater>
</asp:Content>

